INSERT INTO banks(name) VALUES ('Bank Indonesia (BI)') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Mandiri Bank') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Negara Indonesia (BNI)') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Rakyat Indonesia (BRI)') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Tabungan Negara (BTN)') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank BRI Agroniaga') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Anda') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Artha Graha Internasional') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Bukopin') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Bumi Arta') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Capital Indonesia') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Central Asia (BCA)') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank CIMB Niaga') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Danamon Indonesia') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Ekonomi Raharja') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Ganesha') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank KEB Hana') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Woori Saudara') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank ICBC Indonesia') ON CONFLICT (name) DO NOTHING;
INSERT INTO banks(name) VALUES ('Bank Index Selindo') ON CONFLICT (name) DO NOTHING;
