// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CartItemUsecase is an autogenerated mock type for the CartItemUsecase type
type CartItemUsecase struct {
	mock.Mock
}

// AddItemToCart provides a mock function with given fields: ctx, customerID, itemID
func (_m *CartItemUsecase) AddItemToCart(ctx context.Context, customerID uuid.UUID, itemID uuid.UUID) error {
	ret := _m.Called(ctx, customerID, itemID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, customerID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveItemFromCart provides a mock function with given fields: ctx, customerID, itemID
func (_m *CartItemUsecase) RemoveItemFromCart(ctx context.Context, customerID uuid.UUID, itemID uuid.UUID) error {
	ret := _m.Called(ctx, customerID, itemID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, customerID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
