// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/OLTeam-go/sea-store-backend-transactions/models"

	uuid "github.com/google/uuid"
)

// CartRepository is an autogenerated mock type for the CartRepository type
type CartRepository struct {
	mock.Mock
}

// FetchHistoryByCustomerID provides a mock function with given fields: ctx, id, page
func (_m *CartRepository) FetchHistoryByCustomerID(ctx context.Context, id uuid.UUID, page int) ([]*models.Cart, error) {
	ret := _m.Called(ctx, id, page)

	var r0 []*models.Cart
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []*models.Cart); ok {
		r0 = rf(ctx, id, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, id, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveByCustomerID provides a mock function with given fields: ctx, id
func (_m *CartRepository) GetActiveByCustomerID(ctx context.Context, id uuid.UUID) (*models.Cart, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Cart
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Cart); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CartRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Cart, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Cart
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Cart); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, cart
func (_m *CartRepository) Update(ctx context.Context, cart models.Cart) error {
	ret := _m.Called(ctx, cart)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Cart) error); ok {
		r0 = rf(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
