INSERT INTO banks(name) VALUES
 ('Bank Indonesia (BI)')
,('Bank Mandiri Bank')
,('Bank Negara Indonesia (BNI)')
,('Bank Rakyat Indonesia (BRI)')
,('Bank Tabungan Negara (BTN)')
,('Bank BRI Agroniaga')
,('Bank Anda')
,('Bank Artha Graha Internasional')
,('Bank Bukopin')
,('Bank Bumi Arta')
,('Bank Capital Indonesia')
,('Bank Central Asia (BCA)')
,('Bank CIMB Niaga')
,('Bank Danamon Indonesia')
,('Bank Ekonomi Raharja')
,('Bank Ganesha')
,('Bank KEB Hana')
,('Bank Woori Saudara')
,('Bank ICBC Indonesia')
,('Bank Index Selindo');
